name: Continuous integration

on:
  push:
  pull_request:
    branches:
      - develop
      - main

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '5.7'
          coverage: xdebug
          mysql database: 'mercatodo'
          mysql root password: 'password'

      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: '8.0'

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --no-suggest

      - name: Check code style
        run: composer run-script php-cs-fixer-check

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Install Passport
        run: php artisan passport:keys

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: composer run-script testdox

      - name: Prepare paths for SonarQube analysis
        run: |
          sed -i "s|$GITHUB_WORKSPACE|/github/workspace|g" phpunit.report.xml
          sed -i "s|$GITHUB_WORKSPACE|/github/workspace|g" phpunit.coverage.xml

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
